apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    name: url-shortener
spec:
  replicas: 3
  selector: 
   matchLabels:
     name: url-shortener
  template:
    metadata:
     labels:
       name: url-shortener
    spec:
      hostNetwork: true
      volumes:
        -
          name: zerotier
          hostPath:
            path: /var/lib/zerotier-one
        - 
          name: dev-net-tun
          hostPath:
            path: /dev/net/tun
      containers:
        -
          name: url-shortener
          volumeMounts:
            -
              name: zerotier
              mountPath: /var/lib/zerotier-one
            - 
              readOnly: true
              name: dev-net-tun
              mountPath: /dev/net/tun
          image: wscs1958/url-shortener-final
          ports:
            -
              containerPort: 8080
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN


