apiVersion: v1
kind: Service
metadata:
  labels:
    name: url-shortener
  name: url-shortener
spec:
  ports:
  - nodePort: 30500
    port: 8080
    protocol: TCP
    targetPort: 8080
  clusterIP: 10.100.0.78
  selector:
    name: url-shortener
  type: NodePort
